# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lifting Progress Tracker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  # Pods for Lifting Progress Tracker
source 'https://github.com/CocoaPods/Specs.git'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'GoogleSignIn'
pod 'Firebase/Database'
end
